### ISSUE TITLE
Fallo en el itinerario del Tema 2

### ISSUE THREAD

**Issue by Zanderiyo** [latacita/IngenieriaRequisitos#2]
Las tareas T09a y T09b piden explicar lo mismo. 

Se sugiere que la tarea T09b se centre explicar la vista de utilización.

**Comment by latacita** [comment]
Se ha corregido la descripción de la tarea. 

En realidad lo incorrecto, por exceso de copia y pega, era la segunda frase de la tarea, ya que la primera parte hacía referencia a la vista de utilización (_usage facet_).

Por favor, confirma que la incidencia ha sido adecuadamente resuelta.

**Comment by Zanderiyo** [comment]
Incidencia resuelta
