### ISSUE TITLE
Práctica 1 - Errores tipográficos

### ISSUE THREAD

**Issue by swfer** [latacita/IngenieriaRequisitos#3]
Se ha detectado que el cuerpo del documento contiene algunas erratas:

“determinar cuál es ese objetivo satisfacer”
“no desarrollamos software forma altruista”

Se sugiere su cambio a:

“determinar cuál es ese objetivo **a** satisfacer”
“no desarrollamos software **de** forma altruista”

**Comment by latacita** [comment]
Las erratas aparecen en la introducción. 

Indica la próxima vez dónde se encuentran, para que sea más fácil su localización.

**Comment by latacita** [comment]
Errores tipográficos corregidos. 

Por favor, verifica que la nueva versión corregida está en moodle y que los errores reportados han sido efectivamente corregidos.

Muchas gracias por tu colaboración.

**Comment by swfer** [comment]
De acuerdo.

Confirmo que la nueva versión está en Moodle y que los errores han sido corregidos.
